export const projects = [
  {
    id: 0,
    title: "ACI SH.A",
    description: "ACI SH.A është themeluar në vitin 2003, si një kompani e shitjes dhe shpërndarjes së vajrave lubrifikantë. ekipi themelues ishte i specializuar në tregun produkteve te naftes me një ekperiencë të gjatë në kompani të tjera. që në fillimet e saj, kompania jonë ishte e përqendruar në shpërndarjen e produkteve PETROGAL nën emrin e markës GALP, duke pasur ekskluzivitet në territorin shqiptar për këto produkte. ne gjithmonë përpiqemi që të ruajmë një bashkëpunim të mirë me klientët tanë si edhe të ofrojmë një shërbim të shkëlqyer dhe me vlerë të kënaqshme. cilësia e produkteve që ofron kompania jonë është e garantuar nga galp përmes programit të partneritetit midis dy kompanive.",
    url: "https://acilub.vercel.app/",
    imageUrl: "/images/aci-logo/aci-logo-dark-demo.jpg",
    repo: "https://github.com/AlviDervishaj/ACI.SH.A",
    categories: ["web_dev"],
  },
  {
    id: 1,
    title: "Albanianslate",
    description: "Albanianslate është një aplikacion i thjeshtë dhe efektiv që lejon përdoruesit të shkarkojnë videot e tyre të preferuara nga YouTube dhe të përkthejnë titrat e tyre në shqip. Thjesht futni URL-në e videos dhe Albanianslate do t&apos;a shkarkojë dhe përkthejë titrat për ju. ",
    imageUrl: "/images/albanianslate-logo/svg/logo-no-background.svg",
    repo: "https://github.com/AlviDervishaj/Albanianslate",
    categories: ["web_dev"],
  },
  {
    id: 2,
    title: "Gymify",
    description: " Gymify është një aplikacion gjithëpërfshirës i krijuar për të racionalizuar operacionet e zinxhirëve të palestrave. Nga menaxhimi i anëtarësive dhe rezervimeve deri te monitorimi i pjesëmarrjes dhe gjenerimi i raporteve, Gymify ofron një zgjidhje të vetme për pronarët dhe menaxherët e palestrave. Me interfacen e tij përdorues-miqësor dhe veçoritë e fuqishme, Gymify ju ndihmon të optimizoni performancën e palestërve tuaj dhe të ofroni përvoja të jashtëzakonshme për klientët.",
    imageUrl: "/images/gymify-logo/svg/logo-no-background.svg",
    repo: "https://github.com/Gymifyy/Gymify",
    categories: ["web_dev"],
  },
  {
    id: 3,
    title: "Rite Electric",
    description: "Rite Electric LLC fokusohet në ndërtimin dhe mirëmbajtjen elektrike. Disa nga shërbimet e tyre përfshijnë zgjidhjen e problemeve dhe riparimin e të gjitha instalimeve elektrike të jashtme të brendshme, instalimet e komponentëve për rimodelime dhe shtesa si ndërprerësit e qarkut të defektit në tokë (GFCI), instalime të tensionit të lartë dhe riparime elektrike parandaluese.",
    imageUrl: "/images/rite-logo/new-logo.webp",
    repo: "https://github.com/AlviDervishaj/Rite-Electric",
    categories: ["web_dev"],
  },
  {
    id: 4,
    title: "Config",
    description: "Kjo repo eshte nje config i Arch Linux, Tmux, Neovim, Picom, Rofi, Polybar, Starship, Lazygit, i3, wezterm dhe alacritty per te maksimizuar produktivitetin e nje developer-i.",
    imageUrl: "/images/nice-blue-background.png",
    repo: "https://github.com/AlviDervishaj/config",
    categories: ["termial"],
  },
  {
    id: 5,
    title: "GO LSP",
    description: "LSP_GO është një librari e shkruar në Go, e dizajnuar për të lehtësuar krijimin e LSP (Language Server Protocols) që mund të komunikojnë ekeftivisht me Neovim ne kohe reale. Kjo librari mundeson krijimin e nje framework-u robust duke na dhene mundesine e krijimit te LSP-ve per gjuhe te ndryshme dhe perdorime te ndryshme.",
    imageUrl: "/images/go-lsp-logo/go_lsp.png",
    repo: "https://github.com/AlviDervishaj/LSP_GO",
    categories: ["terminal"],
  },
];

